{
    'name': "Sales Order Total Discount",
    'author': 'FINOUTSOURCE',
    'category': 'Sales/Sales',
    'summary': """Sales Order Total Discount""",
    'description': """ """,
    'version': '1.0',
    'depends': ['base','sale_management'],
    'data': ['views/sale_order_view.xml'],
    'images': ['static/description/banner.png'],
    'license': 'AGPL-3',    
    'installable': True,
    'application': True,
    'auto_install': False,
}
